[package]
name = "functions"
version = "0.1.0"
authors = ["Peter Bødskov <me@peterbodskov.dk>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
